/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.CardLayout;
import java.awt.Dimension;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author Lucas
 */
public class testUI extends JFrame {

	SocietySys socList = new SocietySys();
	StudentSys stuList = new StudentSys();
	Student stu;
	static mainPanel mainP;
	static joinPanel joinP;
	static createPanel createP;
	static loginPanel loginP;
	static socPanel socP;
	static electionPanel elecP;
	static stuCreatePanel stuP;
	private JMenuItem jMenuItem1;
	private JoinFrame joinFrame;
	private CreateFrame createFrame;
	private JPanel mainPanel;
	private JPanel createSociety;
	private JPanel joinSociety;
	private JPanel loginPanel;
	private JLabel welcomeLabel;
	private JButton joinButton;
	private JButton createButton;
	private JList<String> jList1;
	private JScrollPane jScrollPane1;
	private JLabel lblMySocieties;
	private JButton joinBtn;
	private JButton leaveBtn;
	private JScrollPane scrollPane_1;
	private JList list_1;
	private JButton btnBack;
	private JLabel emailLbl;
	private JLabel majorLbl;
	private JLabel descriptLbl;
	private JLabel socNameLbl;
	private JTextField textField;
	private JTextField textField_1;
	private JTextField textField_2;
	private JTextField textField_3;
	private JLabel lblPleaseLogIn;
	private JLabel lblName;
	private JTextField nameField;
	private JLabel lblDontHaveAn;
	private JButton btnClickHereTo;
	private JButton btnLogIn;
	private JPanel socPanel;
	private JLabel label;
	private JLabel lblNewLabel;
	private JButton btnBack_2;

	/**
	 * Creates new form testUI
	 */

	public testUI(SocietySys societyManager, StudentSys studentManager) {
		setTitle("MUN Society System");
		socList = societyManager;
		stuList = studentManager;
		socList.loadSocietyList();
		stuList.loadStuList();
		stu = stuList.getStuLoggedIn();
		setResizable(false);
		
		initComponents();
	}



	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		
		 // change when log in works, right now
									// everthing is done from "Lucas" student
									// login
		
		
		this.getContentPane().setPreferredSize(new Dimension(900, 600));
		getContentPane().setLayout(new CardLayout(0, 0));
		mainP = new mainPanel(socList, stuList, stu);
		getContentPane().add(mainP, "name_1327774427254");
		joinP = new joinPanel(socList, stuList, stu);
		GroupLayout groupLayout = (GroupLayout) joinP.getLayout();
		groupLayout.setAutoCreateGaps(true);
		getContentPane().add(joinP, "name_1327794257638");
		createP = new createPanel(socList, stuList, stu);
		getContentPane().add(createP);
		loginP = new loginPanel(socList, stuList);
		getContentPane().add(loginP);
		socP = new socPanel(socList, stuList, stu);
		getContentPane().add(socP);
		elecP = new electionPanel(socList, stuList);
		getContentPane().add(elecP);
		stuP = new stuCreatePanel(socList, stuList);
		getContentPane().add(stuP);
		
		//loginP.setVisible(true);
		socP.setVisible(false);
		mainP.setVisible(true);
		joinP.setVisible(false);
		createP.setVisible(false);
		elecP.setVisible(false);
		stuP.setVisible(false);
		pack();
	}

	/*
	 * mainPanel = new JPanel(); getContentPane().add(mainPanel,
	 * "name_895231091421143"); //jScrollPane1 = new JScrollPane(); //jList1 =
	 * new JList<>(); //jScrollPane1.setViewportView(jList1);
	 * 
	 * //welcomeLabel = new JLabel(
	 * "Welcome to the Memorial University Society System");
	 * //welcomeLabel.setForeground(new Color(128, 0, 0));
	 * //welcomeLabel.setFont(new Font("Tahoma", Font.BOLD, 26));
	 * 
	 * joinButton = new JButton("Join Society");
	 * joinButton.addActionListener(new ActionListener() { public void
	 * actionPerformed(ActionEvent e) { mainPanel.setVisible(false);
	 * joinSociety.setVisible(true);
	 * 
	 * } }); JScrollPane scrollPane = new JScrollPane();
	 * scrollPane.setMaximumSize(new Dimension(200, 200));
	 * 
	 * 
	 * JList list = new JList();
	 * list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
	 * scrollPane.setViewportView(list); final DefaultListModel model = new
	 * DefaultListModel();
	 * 
	 * for (Society s : socList.getSocietyList()) { if (s.isMember(stu))
	 * model.addElement(s.getName()); } list.setModel(model);
	 * list.addMouseListener(new MouseAdapter() { public void
	 * mouseClicked(MouseEvent evt) { JList listt = (JList)evt.getSource(); if
	 * (evt.getClickCount() == 2) {
	 * 
	 * // Double-click detected int index =
	 * listt.locationToIndex(evt.getPoint()); mainPanel.setVisible(false);
	 * socPanel.setVisible(true);
	 * 
	 * 
	 * 
	 * } else if (evt.getClickCount() == 3) {
	 * 
	 * // Triple-click detected int index =
	 * listt.locationToIndex(evt.getPoint()); } } }); createButton = new
	 * JButton("Create Society"); createButton.addActionListener(new
	 * ActionListener() { public void actionPerformed(ActionEvent e) {
	 * mainPanel.setVisible(false); createSociety.setVisible(true); } });
	 * 
	 * lblMySocieties = new JLabel("My Societies"); lblMySocieties.setFont(new
	 * Font("Tahoma", Font.PLAIN, 24)); GroupLayout gl_mainPanel = new
	 * GroupLayout(mainPanel); gl_mainPanel.setHorizontalGroup(
	 * gl_mainPanel.createParallelGroup(Alignment.LEADING)
	 * .addGroup(gl_mainPanel.createSequentialGroup() .addGap(10)
	 * .addComponent(welcomeLabel, GroupLayout.PREFERRED_SIZE, 900,
	 * GroupLayout.PREFERRED_SIZE))
	 * .addGroup(gl_mainPanel.createSequentialGroup() .addGap(54)
	 * .addGroup(gl_mainPanel.createParallelGroup(Alignment.LEADING)
	 * .addComponent(lblMySocieties, GroupLayout.PREFERRED_SIZE, 160,
	 * GroupLayout.PREFERRED_SIZE) .addComponent(scrollPane,
	 * GroupLayout.PREFERRED_SIZE, 195, GroupLayout.PREFERRED_SIZE))
	 * .addGap(407)
	 * .addGroup(gl_mainPanel.createParallelGroup(Alignment.LEADING)
	 * .addComponent(createButton, GroupLayout.PREFERRED_SIZE, 167,
	 * GroupLayout.PREFERRED_SIZE) .addComponent(joinButton,
	 * GroupLayout.PREFERRED_SIZE, 167, GroupLayout.PREFERRED_SIZE))) );
	 * gl_mainPanel.setVerticalGroup(
	 * gl_mainPanel.createParallelGroup(Alignment.LEADING)
	 * .addGroup(gl_mainPanel.createSequentialGroup() .addGap(11)
	 * .addComponent(welcomeLabel, GroupLayout.PREFERRED_SIZE, 55,
	 * GroupLayout.PREFERRED_SIZE) .addGap(130)
	 * .addGroup(gl_mainPanel.createParallelGroup(Alignment.LEADING)
	 * .addGroup(gl_mainPanel.createSequentialGroup()
	 * .addComponent(lblMySocieties) .addGap(7) .addComponent(scrollPane,
	 * GroupLayout.PREFERRED_SIZE, 327, GroupLayout.PREFERRED_SIZE))
	 * .addGroup(gl_mainPanel.createSequentialGroup() .addComponent(joinButton,
	 * GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE) .addGap(18)
	 * .addComponent(createButton, GroupLayout.PREFERRED_SIZE, 102,
	 * GroupLayout.PREFERRED_SIZE)))) ); mainPanel.setLayout(gl_mainPanel);
	 * 
	 * loginPanel = new JPanel(); getContentPane().add(loginPanel,
	 * "name_895238872963456");
	 * 
	 * lblPleaseLogIn = new JLabel("Please log in:"); lblPleaseLogIn.setFont(new
	 * Font("Tahoma", Font.PLAIN, 30));
	 * 
	 * lblName = new JLabel("Full name:");
	 * 
	 * nameField = new JTextField(); nameField.setColumns(10);
	 * 
	 * lblDontHaveAn = new JLabel("Don't have an account?");
	 * 
	 * btnClickHereTo = new JButton("Click here to make one");
	 * 
	 * btnLogIn = new JButton("Log in"); btnLogIn.addActionListener(new
	 * ActionListener() { public void actionPerformed(ActionEvent e) { for
	 * (Student s : stuList.getStuList()) { if
	 * (nameField.getText().equalsIgnoreCase(s.getName())) { stu =
	 * stuList.getStudent(s.getName()); loginPanel.setVisible(false);
	 * mainPanel.setVisible(true); } else { System.out.println("Not registered"
	 * ); }
	 * 
	 * } if (nameField.getText().equals("")) {
	 * JOptionPane.showMessageDialog(null, "Please enter your name", "Error",
	 * JOptionPane.ERROR_MESSAGE); } mainPanel.revalidate();
	 * mainPanel.repaint();
	 * 
	 * } }); GroupLayout gl_loginPanel = new GroupLayout(loginPanel);
	 * gl_loginPanel.setHorizontalGroup(gl_loginPanel.createParallelGroup(
	 * Alignment.LEADING) .addGroup(gl_loginPanel.createSequentialGroup()
	 * .addGroup(gl_loginPanel.createParallelGroup(Alignment.LEADING)
	 * .addGroup(gl_loginPanel.createSequentialGroup().addGap(71).addComponent(
	 * lblPleaseLogIn, GroupLayout.PREFERRED_SIZE, 261,
	 * GroupLayout.PREFERRED_SIZE))
	 * .addGroup(gl_loginPanel.createSequentialGroup().addGap(91)
	 * .addGroup(gl_loginPanel.createParallelGroup(Alignment.TRAILING).
	 * addComponent(btnLogIn)
	 * .addGroup(gl_loginPanel.createSequentialGroup().addComponent(lblName).
	 * addGap(31) .addComponent(nameField, GroupLayout.PREFERRED_SIZE,
	 * GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))))
	 * .addContainerGap(568, Short.MAX_VALUE)) .addGroup(Alignment.TRAILING,
	 * gl_loginPanel.createSequentialGroup().addContainerGap(676,
	 * Short.MAX_VALUE) .addComponent(lblDontHaveAn, GroupLayout.PREFERRED_SIZE,
	 * 127, GroupLayout.PREFERRED_SIZE) .addGap(164))
	 * .addGroup(Alignment.TRAILING, gl_loginPanel.createSequentialGroup()
	 * .addContainerGap(722,
	 * Short.MAX_VALUE).addComponent(btnClickHereTo).addGap(156)));
	 * gl_loginPanel.setVerticalGroup(gl_loginPanel.createParallelGroup(
	 * Alignment.LEADING).addGroup(gl_loginPanel
	 * .createSequentialGroup().addGap(59) .addComponent(lblPleaseLogIn,
	 * GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE).addGap(106)
	 * .addGroup(gl_loginPanel.createParallelGroup(Alignment.BASELINE).
	 * addComponent(lblName).addComponent( nameField,
	 * GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
	 * GroupLayout.PREFERRED_SIZE)) .addGroup(
	 * gl_loginPanel.createParallelGroup(Alignment.LEADING)
	 * .addGroup(gl_loginPanel.createSequentialGroup().addGap(18)
	 * .addComponent(lblDontHaveAn, GroupLayout.PREFERRED_SIZE, 32,
	 * GroupLayout.PREFERRED_SIZE)
	 * .addPreferredGap(ComponentPlacement.UNRELATED).addComponent(
	 * btnClickHereTo))
	 * .addGroup(gl_loginPanel.createSequentialGroup().addGap(36).addComponent(
	 * btnLogIn))) .addContainerGap(284, Short.MAX_VALUE)));
	 * loginPanel.setLayout(gl_loginPanel);
	 * 
	 * 
	 * createSociety = new JPanel();
	 * 
	 * getContentPane().add(createSociety, "name_895235596351668");
	 * 
	 * emailLbl = new JLabel("Email:");
	 * 
	 * majorLbl = new JLabel("Major:");
	 * 
	 * descriptLbl = new JLabel("One line description:");
	 * 
	 * socNameLbl = new JLabel("Society name:");
	 * 
	 * textField = new JTextField(); textField.setColumns(10);
	 * 
	 * textField_1 = new JTextField(); textField_1.setColumns(10);
	 * 
	 * textField_2 = new JTextField(); textField_2.setColumns(10);
	 * 
	 * textField_3 = new JTextField(); textField_3.setColumns(10);
	 * 
	 * JButton btnOk = new JButton("OK"); btnOk.addActionListener(new
	 * ActionListener() { public void actionPerformed(ActionEvent e) { if
	 * (textField.getText().equals("")) { JOptionPane.showMessageDialog(null,
	 * "Please enter the society name", "Error", JOptionPane.ERROR_MESSAGE); }
	 * else if (textField_1.getText().equals("")) {
	 * JOptionPane.showMessageDialog(null, "Please enter your email", "Error",
	 * JOptionPane.ERROR_MESSAGE); } else if (textField_2.getText().equals(""))
	 * { JOptionPane.showMessageDialog(null, "Please enter a major", "Error",
	 * JOptionPane.ERROR_MESSAGE); } else if (textField_3.getText().equals(""))
	 * { JOptionPane.showMessageDialog(null, "Please enter a 1 line description"
	 * , "Error", JOptionPane.ERROR_MESSAGE); } else if
	 * (socList.findSociety(textField.getText())) {
	 * JOptionPane.showMessageDialog(null, "That Society already exists",
	 * "Error", JOptionPane.ERROR_MESSAGE); } else { Society newSociety = new
	 * Society(stu, textField.getText(), textField_1.getText(),
	 * textField_2.getText(), textField_3.getText()); socList.loadSocietyList();
	 * socList.addSociety(newSociety); socList.saveSocietyList();
	 * JOptionPane.showMessageDialog(null, "Society '" + textField.getText() +
	 * "' successfully created"); setVisible(false); } } });
	 * 
	 * JButton btnBack_1 = new JButton("Back"); btnBack_1.addActionListener(new
	 * ActionListener() { public void actionPerformed(ActionEvent e) {
	 * createSociety.setVisible(false); mainPanel.setVisible(true); } });
	 * GroupLayout gl_createSociety = new GroupLayout(createSociety);
	 * gl_createSociety.setHorizontalGroup(gl_createSociety.createParallelGroup(
	 * Alignment.LEADING)
	 * .addGroup(gl_createSociety.createSequentialGroup().addGap(77)
	 * .addGroup(gl_createSociety.createParallelGroup(Alignment.LEADING).
	 * addComponent(socNameLbl)
	 * .addComponent(emailLbl).addComponent(majorLbl).addComponent(descriptLbl))
	 * .addGap(45)
	 * .addGroup(gl_createSociety.createParallelGroup(Alignment.LEADING)
	 * .addComponent(textField_3, GroupLayout.PREFERRED_SIZE,
	 * GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
	 * .addComponent(textField_2, GroupLayout.PREFERRED_SIZE,
	 * GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
	 * .addComponent(textField_1, GroupLayout.PREFERRED_SIZE,
	 * GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
	 * .addComponent(textField, GroupLayout.PREFERRED_SIZE,
	 * GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
	 * .addContainerGap(594, Short.MAX_VALUE)) .addGroup(Alignment.TRAILING,
	 * gl_createSociety.createSequentialGroup().addContainerGap(647,
	 * Short.MAX_VALUE)
	 * .addComponent(btnBack_1).addGap(46).addComponent(btnOk).addGap(71)));
	 * gl_createSociety.setVerticalGroup(gl_createSociety.createParallelGroup(
	 * Alignment.LEADING)
	 * .addGroup(gl_createSociety.createSequentialGroup().addGap(76)
	 * .addGroup(gl_createSociety.createParallelGroup(Alignment.BASELINE).
	 * addComponent(socNameLbl) .addComponent(textField,
	 * GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
	 * GroupLayout.PREFERRED_SIZE)) .addGap(36)
	 * .addGroup(gl_createSociety.createParallelGroup(Alignment.BASELINE).
	 * addComponent(emailLbl) .addComponent(textField_1,
	 * GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
	 * GroupLayout.PREFERRED_SIZE)) .addGap(38)
	 * .addGroup(gl_createSociety.createParallelGroup(Alignment.BASELINE).
	 * addComponent(majorLbl) .addComponent(textField_2,
	 * GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
	 * GroupLayout.PREFERRED_SIZE)) .addGap(41)
	 * .addGroup(gl_createSociety.createParallelGroup(Alignment.BASELINE).
	 * addComponent(descriptLbl) .addComponent(textField_3,
	 * GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
	 * GroupLayout.PREFERRED_SIZE))
	 * .addGap(243).addGroup(gl_createSociety.createParallelGroup(Alignment.
	 * BASELINE) .addComponent(btnOk).addComponent(btnBack_1))
	 * .addContainerGap(63, Short.MAX_VALUE)));
	 * createSociety.setLayout(gl_createSociety);
	 * 
	 * joinSociety = new JPanel(); getContentPane().add(joinSociety,
	 * "name_895237341878294");
	 * 
	 * joinBtn = new JButton("Join"); joinBtn.addActionListener(new
	 * ActionListener() { public void actionPerformed(ActionEvent e) { } });
	 * 
	 * leaveBtn = new JButton("Leave");
	 * 
	 * scrollPane_1 = new JScrollPane();
	 * 
	 * btnBack = new JButton("Back"); btnBack.addActionListener(new
	 * ActionListener() { public void actionPerformed(ActionEvent e) {
	 * joinSociety.setVisible(false); mainPanel.setVisible(true); } });
	 * GroupLayout gl_joinSociety = new GroupLayout(joinSociety);
	 * gl_joinSociety.setHorizontalGroup(
	 * gl_joinSociety.createParallelGroup(Alignment.TRAILING)
	 * .addGroup(gl_joinSociety.createSequentialGroup() .addContainerGap()
	 * .addComponent(scrollPane_1, GroupLayout.PREFERRED_SIZE, 348,
	 * GroupLayout.PREFERRED_SIZE)
	 * .addGroup(gl_joinSociety.createParallelGroup(Alignment.LEADING)
	 * .addGroup(gl_joinSociety.createSequentialGroup().addGap(115)
	 * .addGroup(gl_joinSociety.createParallelGroup(Alignment.TRAILING)
	 * .addComponent(joinBtn).addComponent(leaveBtn)) .addContainerGap())
	 * .addGroup(Alignment.TRAILING, gl_joinSociety.createSequentialGroup()
	 * .addPreferredGap(ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
	 * .addComponent(btnBack).addGap(172)))) ); gl_joinSociety.setVerticalGroup(
	 * gl_joinSociety.createParallelGroup(Alignment.TRAILING)
	 * .addGroup(gl_joinSociety.createSequentialGroup() .addGap(180)
	 * .addComponent(joinBtn) .addGap(8) .addComponent(btnBack).addGap(86)
	 * .addComponent(leaveBtn) .addContainerGap(257, Short.MAX_VALUE))
	 * .addGroup(gl_joinSociety.createSequentialGroup() .addContainerGap(114,
	 * Short.MAX_VALUE) .addComponent(scrollPane_1, GroupLayout.PREFERRED_SIZE,
	 * 475, GroupLayout.PREFERRED_SIZE) .addContainerGap()) );
	 * 
	 * list_1 = new JList();
	 * list_1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
	 * DefaultListModel joinModel = new DefaultListModel(); for (Society s :
	 * socList.getSocietyList()) { joinModel.addElement(s.getName()); }
	 * scrollPane_1.setViewportView(list_1);
	 * 
	 * list_1.setModel(joinModel); list_1.addMouseListener(new MouseAdapter() {
	 * public void mouseClicked(MouseEvent evt) { JList list =
	 * (JList)evt.getSource(); if (evt.getClickCount() == 2) {
	 * 
	 * // Double-click detected int index =
	 * list.locationToIndex(evt.getPoint()); System.out.println("Double click");
	 * } else if (evt.getClickCount() == 3) {
	 * 
	 * // Triple-click detected int index =
	 * list.locationToIndex(evt.getPoint()); } } });
	 * joinSociety.setLayout(gl_joinSociety);
	 * 
	 * socPanel = new JPanel(); getContentPane().add(socPanel,
	 * "name_2162889633728");
	 * 
	 * label = new JLabel("<society name>");
	 * 
	 * 
	 * 
	 * 
	 * 
	 * 
	 * lblNewLabel = new JLabel("<society major>");
	 * 
	 * JScrollPane scrollPane_2 = new JScrollPane();
	 * 
	 * JLabel lblMembers = new JLabel("Members");
	 * 
	 * JButton btnLeaveThisSociety = new JButton("Leave this society");
	 * 
	 * btnBack_2 = new JButton("Back"); btnBack_2.addActionListener(new
	 * ActionListener() { public void actionPerformed(ActionEvent arg0) {
	 * socPanel.setVisible(false); mainPanel.setVisible(true); } }); GroupLayout
	 * gl_socPanel = new GroupLayout(socPanel); gl_socPanel.setHorizontalGroup(
	 * gl_socPanel.createParallelGroup(Alignment.TRAILING)
	 * .addGroup(gl_socPanel.createSequentialGroup() .addGap(101)
	 * .addGroup(gl_socPanel.createParallelGroup(Alignment.LEADING)
	 * .addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 115,
	 * GroupLayout.PREFERRED_SIZE) .addComponent(label,
	 * GroupLayout.PREFERRED_SIZE, 146, GroupLayout.PREFERRED_SIZE))
	 * .addContainerGap(653, Short.MAX_VALUE))
	 * .addGroup(gl_socPanel.createSequentialGroup() .addContainerGap(427,
	 * Short.MAX_VALUE)
	 * .addGroup(gl_socPanel.createParallelGroup(Alignment.LEADING)
	 * .addComponent(lblMembers) .addComponent(scrollPane_2,
	 * GroupLayout.PREFERRED_SIZE, 154, GroupLayout.PREFERRED_SIZE))
	 * .addGap(319)) .addGroup(gl_socPanel.createSequentialGroup() .addGap(66)
	 * .addComponent(btnLeaveThisSociety)
	 * .addPreferredGap(ComponentPlacement.RELATED, 456, Short.MAX_VALUE)
	 * .addComponent(btnBack_2) .addGap(170)) ); gl_socPanel.setVerticalGroup(
	 * gl_socPanel.createParallelGroup(Alignment.LEADING)
	 * .addGroup(gl_socPanel.createSequentialGroup() .addGap(69)
	 * .addComponent(label, GroupLayout.PREFERRED_SIZE, 32,
	 * GroupLayout.PREFERRED_SIZE) .addGap(86) .addComponent(lblNewLabel,
	 * GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE) .addGap(45)
	 * .addComponent(lblMembers) .addPreferredGap(ComponentPlacement.RELATED)
	 * .addComponent(scrollPane_2, GroupLayout.PREFERRED_SIZE, 214,
	 * GroupLayout.PREFERRED_SIZE) .addGap(35)
	 * .addComponent(btnLeaveThisSociety) .addContainerGap(46, Short.MAX_VALUE))
	 * .addGroup(Alignment.TRAILING, gl_socPanel.createSequentialGroup()
	 * .addContainerGap(515, Short.MAX_VALUE) .addComponent(btnBack_2)
	 * .addGap(62)) );
	 * 
	 * JList list_2 = new JList(); scrollPane_2.setViewportView(list_2);
	 * DefaultListModel memModel = new DefaultListModel(); for (Society s :
	 * socList.getSocietyList()) { memModel.addElement(s.getName()); }
	 * scrollPane_1.setViewportView(list_1);
	 * 
	 * list_1.setModel(joinModel); socPanel.setLayout(gl_socPanel); this.pack();
	 * new JPopupMenu(); jMenuItem1 = new JMenuItem(); new JCheckBoxMenuItem();
	 * joinFrame = new JoinFrame();
	 * 
	 * 
	 * jMenuItem1.setText("jMenuItem1"); jMenuItem1.addActionListener(new
	 * java.awt.event.ActionListener() { public void
	 * actionPerformed(java.awt.event.ActionEvent evt) {
	 * jMenuItem1ActionPerformed(evt); } });
	 * 
	 * setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
	 * 
	 * 
	 * 
	 * }// </editor-fold>//GEN-END:initComponents
	 * 
	 * private void jMenuItem1ActionPerformed(ActionEvent evt) {//
	 * GEN-FIRST:event_jMenuItem1ActionPerformed // TODO add your handling code
	 * here: }// GEN-LAST:event_jMenuItem1ActionPerformed
	 * 
	 * /**
	 * 
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(testUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(testUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(testUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(testUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				SocietySys socList = new SocietySys();
				StudentSys stuList = new StudentSys();
				socList.loadSocietyList();
				stuList.loadStuList();
				new testUI(socList, stuList).setVisible(true);
			}
		});
	}
}

